#!/usr/bin/env bash
set -ex
HERE=$(dirname $0)

export VAULT_ADDR='https://vault.dide.ic.ac.uk:8200'
if [ "$VAULT_AUTH_GITHUB_TOKEN" = "" ]; then
    echo -n "Please provide your GitHub personal access token for the vault: "
    read -s token
    echo ""
    export VAULT_AUTH_GITHUB_TOKEN=${token}
fi
echo "Authenticating with the Vault"
vault login -method=github >/dev/null

WEBHOOK_SECRET=$(vault read -field=secret /secret/orderly-bot/webhook-secret)
GH_AUTH_TOKEN=$(vault read -field=token /secret/orderly-bot/auth-token)
echo "[webhook_secrets]
WEBHOOK_SECRET=${WEBHOOK_SECRET}
GH_AUTH_TOKEN=${GH_AUTH_TOKEN}
" >>$HERE/.webhook_secrets.ini
